CXX=g++
CXXFLAGS=-g -std=c++17 -flto -Os -w
SRC=np_simple.cpp
SRC1=np_single_proc.cpp
BIN=np_simple
BIN1=np_single_proc
all:
	$(CXX) -o $(BIN) $(SRC) $(CXXFLAGS)
	$(CXX) -o $(BIN1) $(SRC1) $(CXXFLAGS)
